//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAutoRefTestTeacher
    {
        public int AutoRefTeacherId { get; set; }
        public string AutoRefTeacherTransId { get; set; }
        public Nullable<System.DateTime> AutoRefTeacherTransDate { get; set; }
        public Nullable<int> TeacherAutoId { get; set; }
        public string Right_Spherical_Status { get; set; }
        public Nullable<decimal> Right_Spherical_Points { get; set; }
        public string Right_Cyclinderical_Status { get; set; }
        public Nullable<decimal> Right_Cyclinderical_Points { get; set; }
        public Nullable<int> Right_Axix_From { get; set; }
        public Nullable<int> Right_Axix_To { get; set; }
        public string Left_Spherical_Status { get; set; }
        public Nullable<decimal> Left_Spherical_Points { get; set; }
        public string Left_Cyclinderical_Status { get; set; }
        public Nullable<decimal> Left_Cyclinderical_Points { get; set; }
        public Nullable<int> Left_Axix_From { get; set; }
        public Nullable<int> Left_Axix_To { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntDate { get; set; }
        public string EntOperation { get; set; }
        public string EntTerminal { get; set; }
        public string EntTerminalIP { get; set; }
        public string ApplicationID { get; set; }
        public string FormId { get; set; }
        public Nullable<int> UserEmpId { get; set; }
        public string UserEmpName { get; set; }
        public string UserEmpCode { get; set; }
    }
}
