//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        public int DoctorAutoId { get; set; }
        public string DoctorDescription { get; set; }
        public Nullable<int> HospitalAutoID { get; set; }
        public Nullable<int> SpecialistIn { get; set; }
        public string Category { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> Surgeon { get; set; }
        public Nullable<int> Ophthalmologist { get; set; }
        public Nullable<int> Orthoptist { get; set; }
        public Nullable<int> Optometrist { get; set; }
    }
}
