//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHospital
    {
        public int HospitalAutoId { get; set; }
        public string HospitalDescription { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string Town { get; set; }
        public string City { get; set; }
        public string ContactNo { get; set; }
    }
}
