//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRole
    {
        public int RoleAutoId { get; set; }
        public string RoleDescription { get; set; }
        public string Delflag { get; set; }
        public Nullable<int> City { get; set; }
    }
}
