//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentAuditTrail
    {
        public int tblStudent_Id { get; set; }
        public Nullable<int> StudentAutoId { get; set; }
        public Nullable<int> SchoolAutoId { get; set; }
        public Nullable<int> ClassAutoId { get; set; }
        public string StudentCode { get; set; }
        public string StudentName { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> GenderAutoId { get; set; }
        public Nullable<int> DecreasedVision { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntDate { get; set; }
        public string EntOperation { get; set; }
        public string EntTerminal { get; set; }
        public string EntTerminalIP { get; set; }
        public Nullable<int> WearGlasses { get; set; }
        public Nullable<int> HasOccularHistory { get; set; }
        public string OccularHistoryRemarks { get; set; }
        public Nullable<int> HasMedicalHistory { get; set; }
        public string MedicalHistoryRemarks { get; set; }
        public Nullable<int> HasChiefComplain { get; set; }
        public string ChiefComplainRemarks { get; set; }
        public Nullable<System.DateTime> StudentTestDate { get; set; }
        public string StudentRegNo { get; set; }
        public Nullable<int> SectionAutoId { get; set; }
    }
}
