//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTreatmentStudentAuditTrail
    {
        public int tblTreatmentStudent_Id { get; set; }
        public Nullable<int> TreatmentStudentId { get; set; }
        public Nullable<System.DateTime> TreatmentStudentTransDate { get; set; }
        public Nullable<int> StudentAutoId { get; set; }
        public string Daignosis { get; set; }
        public string DaignosisRemarks { get; set; }
        public Nullable<int> SubDaignosis { get; set; }
        public string MotherName { get; set; }
        public string MotherCell { get; set; }
        public string FatherCell { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public Nullable<int> Treatment { get; set; }
        public Nullable<int> SubTreatment { get; set; }
        public string MedicineAutoId { get; set; }
        public Nullable<int> NextVisit { get; set; }
        public Nullable<int> Surgery { get; set; }
        public Nullable<int> Referal { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntDate { get; set; }
        public string EntOperation { get; set; }
        public string EntTerminal { get; set; }
        public string EntTerminalIP { get; set; }
        public Nullable<int> SurgeryDetail { get; set; }
        public string SurgeryDetailRemarks { get; set; }
        public string Town { get; set; }
    }
}
