//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int UserAutoId { get; set; }
        public string UserId { get; set; }
        public byte[] Password { get; set; }
        public string Username { get; set; }
        public string email { get; set; }
        public string recoverypin { get; set; }
        public Nullable<System.DateTime> recoveryvalidupto { get; set; }
        public string Delflag { get; set; }
    }
}
