//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVisitFundoscopyStudent
    {
        public int VisitFundoscopyStudentId { get; set; }
        public Nullable<System.DateTime> VisitFundoscopyStudentTransDate { get; set; }
        public Nullable<int> StudentAutoId { get; set; }
        public Nullable<int> HospitalAutoId { get; set; }
        public Nullable<int> DoctorAutoId { get; set; }
        public string Fundoscopyfindings_RightEye { get; set; }
        public string Fundoscopyfindings_LeftEye { get; set; }
        public string Remarks_Fundoscopyfindings { get; set; }
        public string Diagnosis_RightEye { get; set; }
        public string Diagnosis_LeftEye { get; set; }
        public string MedicinePrescribed { get; set; }
        public string OphthalmologistRemarks { get; set; }
        public Nullable<int> SurgerySuggested { get; set; }
        public string SubDiagnosis_RightEye { get; set; }
        public string SubDiagnosis_LeftEye { get; set; }
        public Nullable<int> RoutineCheckup { get; set; }
        public Nullable<System.DateTime> RoutineCheckupDate { get; set; }
        public Nullable<int> FurtherAssessment { get; set; }
        public Nullable<System.DateTime> FurtherAssessmentDate { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntDate { get; set; }
        public string EntOperation { get; set; }
        public string EntTerminal { get; set; }
        public string EntTerminalIP { get; set; }
        public string Fundoscopyfindings_RightEye_Posterior { get; set; }
        public string Fundoscopyfindings_LeftEye_Posterior { get; set; }
        public string Daignosis { get; set; }
        public string DaignosisRemarks { get; set; }
        public string SubDaignosis { get; set; }
        public Nullable<int> SubTreatment { get; set; }
        public Nullable<int> FundoscopyType { get; set; }
        public Nullable<int> SurgeryFollowup { get; set; }
        public Nullable<System.DateTime> SurgeryDate { get; set; }
        public Nullable<int> Normal_RightEye { get; set; }
        public Nullable<int> RefractiveError_RightEye { get; set; }
        public Nullable<int> LowVision_RightEye { get; set; }
        public Nullable<int> NeedsCycloplegicRefraction_RightEye { get; set; }
        public Nullable<int> SquintStrabismus_RightEye { get; set; }
        public Nullable<int> LazyEyeAmblyopia_RightEye { get; set; }
        public Nullable<int> ColorblindnessAchromatopsia_RightEye { get; set; }
        public Nullable<int> Cataract_RightEye { get; set; }
        public Nullable<int> TraumaticCataract_RightEye { get; set; }
        public Nullable<int> Keratoconus_RightEye { get; set; }
        public Nullable<int> Anisometropia_RightEye { get; set; }
        public Nullable<int> Ptosis_RightEye { get; set; }
        public Nullable<int> Nystagmus_RightEye { get; set; }
        public Nullable<int> Corneadefects_RightEye { get; set; }
        public Nullable<int> Puplidefects_RightEye { get; set; }
        public Nullable<int> Pterygium_RightEye { get; set; }
        public Nullable<int> Other_RightEye { get; set; }
        public Nullable<int> Normal_LeftEye { get; set; }
        public Nullable<int> RefractiveError_LeftEye { get; set; }
        public Nullable<int> LowVision_LeftEye { get; set; }
        public Nullable<int> NeedsCycloplegicRefraction_LeftEye { get; set; }
        public Nullable<int> SquintStrabismus_LeftEye { get; set; }
        public Nullable<int> LazyEyeAmblyopia_LeftEye { get; set; }
        public Nullable<int> ColorblindnessAchromatopsia_LeftEye { get; set; }
        public Nullable<int> Cataract_LeftEye { get; set; }
        public Nullable<int> TraumaticCataract_LeftEye { get; set; }
        public Nullable<int> Keratoconus_LeftEye { get; set; }
        public Nullable<int> Anisometropia_LeftEye { get; set; }
        public Nullable<int> Ptosis_LeftEye { get; set; }
        public Nullable<int> Nystagmus_LeftEye { get; set; }
        public Nullable<int> Corneadefects_LeftEye { get; set; }
        public Nullable<int> Puplidefects_LeftEye { get; set; }
        public Nullable<int> Pterygium_LeftEye { get; set; }
        public Nullable<int> Other_LeftEye { get; set; }
        public string DaignosisRemarks_LeftEye { get; set; }
        public Nullable<int> SubDaignosis_LeftEye { get; set; }
    }
}
