//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVisitSixMonthStudent
    {
        public int VisitSixMonthStudentId { get; set; }
        public Nullable<System.DateTime> VisitSixMonthStudentTransDate { get; set; }
        public Nullable<int> StudentAutoId { get; set; }
        public Nullable<int> DistanceVision_RightEye_Unaided { get; set; }
        public Nullable<int> DistanceVision_RightEye_WithGlasses { get; set; }
        public Nullable<int> DistanceVision_RightEye_PinHole { get; set; }
        public Nullable<int> NearVision_RightEye { get; set; }
        public Nullable<int> DistanceVision_LeftEye_Unaided { get; set; }
        public Nullable<int> DistanceVision_LeftEye_WithGlasses { get; set; }
        public Nullable<int> DistanceVision_LeftEye_PinHole { get; set; }
        public Nullable<int> NearVision_LeftEye { get; set; }
        public string Right_Spherical_Status_AutoRef { get; set; }
        public Nullable<decimal> Right_Spherical_Points_AutoRef { get; set; }
        public string Right_Cyclinderical_Status_AutoRef { get; set; }
        public Nullable<decimal> Right_Cyclinderical_Points_AutoRef { get; set; }
        public Nullable<int> Right_Axix_From_AutoRef { get; set; }
        public Nullable<int> Right_Axix_To_AutoRef { get; set; }
        public string Left_Spherical_Status_AutoRef { get; set; }
        public Nullable<decimal> Left_Spherical_Points_AutoRef { get; set; }
        public string Left_Cyclinderical_Status_AutoRef { get; set; }
        public Nullable<decimal> Left_Cyclinderical_Points_AutoRef { get; set; }
        public Nullable<int> Left_Axix_From_AutoRef { get; set; }
        public Nullable<int> Left_Axix_To_AutoRef { get; set; }
        public Nullable<int> RetinoScopy_RightEye { get; set; }
        public string CycloplegicRefraction_RightEye { get; set; }
        public string Condition_RightEye { get; set; }
        public string Meridian1_RightEye { get; set; }
        public string Meridian2_RightEye { get; set; }
        public string FinalPrescription_RightEye { get; set; }
        public Nullable<int> RetinoScopy_LeftEye { get; set; }
        public string CycloplegicRefraction_LeftEye { get; set; }
        public string Condition_LeftEye { get; set; }
        public string Meridian1_LeftEye { get; set; }
        public string Meridian2_LeftEye { get; set; }
        public string FinalPrescription_LeftEye { get; set; }
        public string Right_Spherical_Status { get; set; }
        public Nullable<decimal> Right_Spherical_Points { get; set; }
        public string Right_Cyclinderical_Status { get; set; }
        public Nullable<decimal> Right_Cyclinderical_Points { get; set; }
        public Nullable<int> Right_Axix_From { get; set; }
        public Nullable<int> Right_Axix_To { get; set; }
        public string Right_Near_Status { get; set; }
        public Nullable<decimal> Right_Near_Points { get; set; }
        public string Left_Spherical_Status { get; set; }
        public Nullable<decimal> Left_Spherical_Points { get; set; }
        public string Left_Cyclinderical_Status { get; set; }
        public Nullable<decimal> Left_Cyclinderical_Points { get; set; }
        public Nullable<int> Left_Axix_From { get; set; }
        public Nullable<int> Left_Axix_To { get; set; }
        public string Left_Near_Status { get; set; }
        public Nullable<decimal> Left_Near_Points { get; set; }
        public Nullable<int> NextVisit { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntDate { get; set; }
        public string EntOperation { get; set; }
        public string EntTerminal { get; set; }
        public string EntTerminalIP { get; set; }
        public string Daignosis { get; set; }
        public string DaignosisRemarks { get; set; }
        public string SubDaignosis { get; set; }
        public Nullable<int> Treatment { get; set; }
        public Nullable<int> SubTreatment { get; set; }
        public string MedicineAutoId { get; set; }
        public Nullable<System.DateTime> NextVisitDate { get; set; }
        public Nullable<int> Normal_RightEye { get; set; }
        public Nullable<int> RefractiveError_RightEye { get; set; }
        public Nullable<int> LowVision_RightEye { get; set; }
        public Nullable<int> NeedsCycloplegicRefraction_RightEye { get; set; }
        public Nullable<int> SquintStrabismus_RightEye { get; set; }
        public Nullable<int> LazyEyeAmblyopia_RightEye { get; set; }
        public Nullable<int> ColorblindnessAchromatopsia_RightEye { get; set; }
        public Nullable<int> Cataract_RightEye { get; set; }
        public Nullable<int> TraumaticCataract_RightEye { get; set; }
        public Nullable<int> Keratoconus_RightEye { get; set; }
        public Nullable<int> Anisometropia_RightEye { get; set; }
        public Nullable<int> Ptosis_RightEye { get; set; }
        public Nullable<int> Nystagmus_RightEye { get; set; }
        public Nullable<int> Corneadefects_RightEye { get; set; }
        public Nullable<int> Puplidefects_RightEye { get; set; }
        public Nullable<int> Pterygium_RightEye { get; set; }
        public Nullable<int> Other_RightEye { get; set; }
        public Nullable<int> Normal_LeftEye { get; set; }
        public Nullable<int> RefractiveError_LeftEye { get; set; }
        public Nullable<int> LowVision_LeftEye { get; set; }
        public Nullable<int> NeedsCycloplegicRefraction_LeftEye { get; set; }
        public Nullable<int> SquintStrabismus_LeftEye { get; set; }
        public Nullable<int> LazyEyeAmblyopia_LeftEye { get; set; }
        public Nullable<int> ColorblindnessAchromatopsia_LeftEye { get; set; }
        public Nullable<int> Cataract_LeftEye { get; set; }
        public Nullable<int> TraumaticCataract_LeftEye { get; set; }
        public Nullable<int> Keratoconus_LeftEye { get; set; }
        public Nullable<int> Anisometropia_LeftEye { get; set; }
        public Nullable<int> Ptosis_LeftEye { get; set; }
        public Nullable<int> Nystagmus_LeftEye { get; set; }
        public Nullable<int> Corneadefects_LeftEye { get; set; }
        public Nullable<int> Puplidefects_LeftEye { get; set; }
        public Nullable<int> Pterygium_LeftEye { get; set; }
        public Nullable<int> Other_LeftEye { get; set; }
        public string DaignosisRemarks_LeftEye { get; set; }
        public Nullable<int> SubDaignosis_LeftEye { get; set; }
    }
}
